#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Entry point for the new argparse-based CLI."""

import re
import sys

from onedigit.cli2 import main_cli2

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    success = main_cli2()
    sys.exit(0 if success else 1)