# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

vars:
  PYTHON_VERSION: '3.12'

tasks:

  default:
    aliases: [help]
    desc: Show this help message
    silent: true
    cmds:
      - echo "Available tasks:"
      - echo ""
      - task --list
      - echo ""
      - echo "  task --list                to see all available tasks"
      - echo "  task --summary <TASK_NAME> to see details about task and subtasks"
      - echo "  task <TASK_NAME>           to run a specific task."
      - echo ""

  # --------------------------------------------------------
  # Setup tasks
  # --------------------------------------------------------

  setup:
    cmds:
      - uv sync -p {{.PYTHON_VERSION}} --all-groups
    desc: prepare a venv and install all Python dependencies using uv

  # --------------------------------------------------------
  # Top level check tasks (static analysis)
  # --------------------------------------------------------

  check:
    cmds:
      - task: clean
      - task: check:ruff
      - task: check:ruff:tests
      - task: check:format
      - task: check:mypy
      - task: check:mypy:tests
      - task: check:bandit
      - task: check:bandit:tests
      - task: check:vulture
    desc: run all checks to validate code health

  check:code:
    cmds:
      - task: clean
      - task: check:ruff
      - task: check:mypy
    desc: run all checks on application code

  check:tests:
    cmds:
      - task: clean
      - task: check:ruff:tests
      - task: check:mypy:tests
    desc: run all checks on test code

  # --------------------------------------------------------
  # Static checks tasks
  # --------------------------------------------------------

  check:ruff:
    aliases: [lint]
    cmds:
      - uv run ruff check src/**/*.py
    desc: lint Python application files

  check:ruff:tests:
    cmds:
      - uv run ruff check tests
    desc: lint Python test files

  check:mypy:
    aliases: [typecheck, types, typing]
    cmds:
      - uv run mypy --ignore-missing-imports src/**/*.py
    desc: run type checking on Python application files

  check:mypy:tests:
    cmds:
      - uv run mypy --ignore-missing-imports tests
    desc: run type checking on Python test files

  check:bandit:
    cmds:
      - uv run bandit -c pyproject.toml -ll -r src
    desc: run security analysis (MED or higher) on Python application files

  check:bandit:tests:
    cmds:
      - uv run bandit -c pyproject.toml -ll -r tests
    desc: run security analysis (MED or higher) on Python test files

  check:vulture:
    ignore_error: true
    cmds:
      - cmd: echo "[WARNING] Dead code checks are not fully accurate; review results carefully."
        silent: true
      - cmd: echo "[VULTURE] checking for dead code in Python application files..."
        silent: true
      - uv run vulture src
      - cmd: echo "[VULTURE] checking for dead code in Python test files..."
        silent: true
      - uv run vulture tests
    desc: check for dead code in Python files

  # --------------------------------------------------------
  # Formatting tasks
  # --------------------------------------------------------

  check:format:
    cmds:
      - uv run ruff format --check src/**/*.py
      - uv run ruff format --check tests
      - prettier --check ./**/*.md
    desc: check format of project files

  fix:format:
    aliases: [fmt, format]
    cmds:
      - task: fix:format:code
      - task: fix:format:tests
      - task: fix:format:docs
    desc: format code, tests and documentation files

  fix:format:code:
    cmds:
      - uv run ruff format src/**/*.py
    desc: format Python main files

  fix:format:tests:
    cmds:
      - uv run ruff format tests
    desc: format Python test files

  fix:format:docs:
    cmds:
      - prettier --write ./**/*.md
    desc: format code, tests and documentation files

  # --------------------------------------------------------
  # Tasks to pre-validate Github Actions
  # --------------------------------------------------------

  actions:dryrun:
    cmds:
      - act -j {{.ACT_JOB}} {{.ACT_ARGS}} --dryrun --strict
    desc: dryrun of the GitHub actions to verify they syntax is correct
    vars:
      ACT_IMAGE: 'catthehacker/ubuntu:act-latest'
      ACT_JOB:   'test'
      ACT_ARGS:  '-P ubuntu-latest={{.ACT_IMAGE}} --rm --verbose'

  actions:
    cmds:
      - act -j {{.ACT_JOB}} {{.ACT_ARGS}}
    desc: run the GitHub actions locally to verify they work
    vars:
      ACT_IMAGE: 'catthehacker/ubuntu:act-latest'
      ACT_JOB:   'test'
      ACT_ARGS:  '-P ubuntu-latest={{.ACT_IMAGE}} --rm --verbose'

  # --------------------------------------------------------
  # Testing tasks
  # --------------------------------------------------------

  test:
    cmds:
    - task: test:units
    - task: test:integration
    - task: test:e2e
    - task: test:benchmarks
    desc: run all tests

  test:coverage:
    cmds:
      - uv run pytest --cov=src --cov-report=term-missing tests
    desc: run unit tests with coverage report

  test:coverage:html:
    cmds:
      - uv run pytest tests --cov=src --cov-report=html
      - echo "Open htmlcov/index.html to view the coverage report"
    desc: run unit tests with HTML coverage report

  test:units:
    cmds:
      - uv run pytest -v --cov-fail-under=80.0 tests
    desc: run unit tests

  # --------------------------------------------------------
  # Testing tasks: integration
  # --------------------------------------------------------

  test:integration:
    cmds:
      - uv run pytest -v --cov-fail-under=80.0 tests
    desc: run integration tests

  # --------------------------------------------------------
  # Testing tasks: end-to-end tests
  # --------------------------------------------------------

  test:e2e:
    sources:
      - 'tests/fixtures/*.txt'
    cmds:
      - for: sources
        cmd: "echo E2E with file {{.ITEM}}"
    desc: run end-to-end tests

  # --------------------------------------------------------
  # Testing tasks: benchmarks
  # --------------------------------------------------------

  test:benchmarks:
    cmds:
      - echo "benchmark will run" uv run pytest -v --no-cov --benchmark-only tests/benchmarks
    generates:
      - ./.benchmarks/
    desc: run performance benchmarks (requires pytest-benchmark)

  # --------------------------------------------------------
  # Dependency management tasks
  # --------------------------------------------------------

  deps:update:
    cmds:
      - uv lock --upgrade --dry-run
      - uv lock --upgrade
      - uv sync --all-groups --dry-run
      - uv sync --all-groups
    desc: update all Python dependencies to their latest versions

  # --------------------------------------------------------
  # Project management tasks
  # --------------------------------------------------------

  todo:
    cmds:
      - echo "[TODO] listing all TODO and FIXME comments in the codebase..."
      - grep -E '#.*(FIXME|DEBUG|TODO|HACK|TEMP)' -R src tests || echo "No TODO/FIXME comments found"
    desc: list all TODO and FIXME comments in the codebase

  build:
    cmds:
      - task: clean
      - uv build
    generates:
      - dist/*
    desc: build the project (source and wheel distributions)

  clean:
    cmds:
      - echo "[CLEAN] cleaning up Python cache files and directories..."
      - find . -type d -name "__pycache__" -exec rm -r {} +
      - find . -type f -name "*.pyc" -delete
      - find . -type f -name "*.pyo" -delete
      - find . -type f -name "*~" -delete
      - rm -rf .benchmarks
      - rm -rf .coverage coverage.xml
      - rm -rf .mypy_cache
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache
      - rm -rf htmlcov
    desc: clean up Python cache files and directories

  # --------------------------------------------------------
  # Other
  # --------------------------------------------------------
