#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import sys

if __name__ == "__main__":
    sys.path.insert(0, "src")

    from onedigit.cli import app

    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    success = app()
    sys.exit(0 if success else 1)
